#!/usr/bin/env python3
"""Ersetzt ASCII-Notschreibweisen in de.json durch korrektes Deutsch (Umlaute, ß)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DE_PATH = ROOT / "src" / "messages" / "de.json"

# Längere zuerst (Substring-Kollisionen vermeiden).
REPLACEMENTS: list[tuple[str, str]] = [
    ("Konfigurationsaenderung", "Konfigurationsänderung"),
    ("Portal-Aktivitaet", "Portal-Aktivität"),
    ("Konto-Aktivitaet", "Konto-Aktivität"),
    ("Sandbox-Zahlung abschliessen", "Sandbox-Zahlung abschließen"),
    ("Mock nur ueber den Test-Webhook-Flow abschliessbar", "Mock nur über den Test-Webhook-Flow abschließbar"),
    ("standardmaessig eingeklappt", "standardmäßig eingeklappt"),
    ("eingeschraenkt/nicht konfiguriert", "eingeschränkt/nicht konfiguriert"),
    ("eingeschraenkter Betrieb", "eingeschränkter Betrieb"),
    ("eingeschraenkte Datenbank", "eingeschränkte Datenbank"),
    ("fuer Skripte und KI", "für Skripte und KI"),
    ("fuer Betrieb und Runbooks", "für Betrieb und Runbooks"),
    ("fuer diese Aktion", "für diese Aktion"),
    ("fuer Live-Handel", "für Live-Handel"),
    ("fuer neue Trades", "für neue Trades"),
    ("fuer den Handel", "für den Handel"),
    ("fuer deinen Plan", "für deinen Plan"),
    ("fuer Lage und Queues", "für Lage und Queues"),
    ("fuer diese Umgebung", "für diese Umgebung"),
    ("fuer diese Filter", "für diese Filter"),
    ("fuer Tickets und KI", "für Tickets und KI"),
    ("fuer Menues und Texte", "für Menüs und Texte"),
    ("fuer Hinweise verbinden", "für Hinweise verbinden"),
    ("fuer technische Nachvollziehbarkeit", "für technische Nachvollziehbarkeit"),
    ("fuer automatische Umsetzung", "für automatische Umsetzung"),
    ("fuer lokale Tests", "für lokale Tests"),
    ("fuer Aufrufe am API-Gateway", "für Aufrufe am API-Gateway"),
    ("fuer dieses Symbol", "für dieses Symbol"),
    ("fuer Profil, Guthaben", "für Profil, Guthaben"),
    ("Geschuetzte Verbindung", "Geschützte Verbindung"),
    ("geschuetzt und nur", "geschützt und nur"),
    ("geschuetzt ueber das Gateway", "geschützt über das Gateway"),
    ("geschuetzte Verbindung", "geschützte Verbindung"),
    ("Ausfuehrungsmodus — technische Details", "Ausführungsmodus — technische Details"),
    ("Ausfuehrungsmodus", "Ausführungsmodus"),
    ("Ausfuehrung und Signal", "Ausführung und Signal"),
    ("Ausfuehrungen (Fills)", "Ausführungen (Fills)"),
    ("Ausfuehrungslage", "Ausführungslage"),
    ("Kerzenuebersicht", "Kerzenübersicht"),
    ("Systemuebersicht", "Systemübersicht"),
    ("Kurzuebersicht", "Kurzübersicht"),
    ("Handelsuebersicht", "Handelsübersicht"),
    ("Backtest-Laeufe", "Backtest-Läufe"),
    ("Haeufige Fehlermuster", "Häufige Fehlermuster"),
    ("juengsten Drift", "jüngsten Drift"),
    ("juengsten Paper-Trades", "jüngsten Paper-Trades"),
    ("Massnahmen", "Maßnahmen"),
    ("Zusammenhaenge", "Zusammenhänge"),
    ("logische Zusammenhaenge", "logische Zusammenhänge"),
    ("Stream-Laengen", "Stream-Längen"),
    ("Schluessel (laut Modell)", "Schlüssel (laut Modell)"),
    ("API-Schluessel hier", "API-Schlüssel hier"),
    ("keine API-Schluessel", "keine API-Schlüssel"),
    ("API-Schluessel fuer", "API-Schlüssel für"),
    ("Deine Schluessel bleiben", "Deine Schlüssel bleiben"),
    ("Verknuepfungs-Link", "Verknüpfungs-Link"),
    ("Telegram-Verknuepfung", "Telegram-Verknüpfung"),
    ("bitte Verknuepfung abschliessen", "bitte Verknüpfung abschließen"),
    ("Verknuepfung richtest", "Verknüpfung richtest"),
    ("mit Telegram verknuepft", "mit Telegram verknüpft"),
    ("Mint uebereinstimmen", "Mint übereinstimmen"),
    ("vollstaendige Instrumentenliste", "vollständige Instrumentenliste"),
    ("Vollstaendige Live-Ansicht", "Vollständige Live-Ansicht"),
    ("vollstaendiges Journal", "vollständiges Journal"),
    ("Signal-Kontext (vollstaendig)", "Signal-Kontext (vollständig)"),
    ("vollstaendiges Kontenuniversum", "vollständiges Kontenuniversum"),
    ("Zur vollstaendigen Health-Seite", "Zur vollständigen Health-Seite"),
    ("ohne alles sofort erledigen zu muessen", "ohne alles sofort erledigen zu müssen"),
    ("wenn du moechtest", "wenn du möchtest"),
    ("ist moeglich", "ist möglich"),
    ("sind moeglich", "sind möglich"),
    ("Mirror moeglich", "Mirror möglich"),
    ("Risiko-Kontrolle moeglich", "Risiko-Kontrolle möglich"),
    ("nicht moeglich", "nicht möglich"),
    ("nur mit gueltiger", "nur mit gültiger"),
    ("gueltige Server-Anmeldung", "gültige Server-Anmeldung"),
    ("gueltiges JSON", "gültiges JSON"),
    ("gueltig bis", "gültig bis"),
    ("ungueltig oder", "ungültig oder"),
    ("ist ungueltig", "ist ungültig"),
    ("JWT ungueltig", "JWT ungültig"),
    ("Operator-JWT ungueltig", "Operator-JWT ungültig"),
    ("Erklaerung anfordern", "Erklärung anfordern"),
    ("Modell-Erklaerung", "Modell-Erklärung"),
    ("KI-Erklaerung", "KI-Erklärung"),
    ("Erklaerpfade", "Erklärungen"),
    ("Erklaerungen", "Erklärungen"),
    ("Erklaerung", "Erklärung"),
    ("Orders ausloesen", "Orders auslösen"),
    ("keine Orders ausloesen", "keine Orders auslösen"),
    ("Ausloesung", "Auslösung"),
    ("ausloesen", "auslösen"),
    ("Zahlungsvorgaenge", "Zahlungsvorgänge"),
    ("wartenden Eintraege", "wartenden Einträge"),
    ("Keine Eintraege", "Keine Einträge"),
    ("Eintraege", "Einträge"),
    ("eintraege", "einträge"),
    ("Schluessel bleiben", "Schlüssel bleiben"),
    ("Schluessel", "Schlüssel"),
    ("standardmaessig", "standardmäßig"),
    ("Zusaetzliche", "Zusätzliche"),
    ("zusaetzlich", "zusätzlich"),
    ("ergaenzende", "ergänzende"),
    ("ergaenzen", "ergänzen"),
    ("eingeschraenkt", "eingeschränkt"),
    ("Eingeschraenkt", "Eingeschränkt"),
    ("voruebergehend", "vorübergehend"),
    ("zurueckgegeben", "zurückgegeben"),
    ("zuruecksetzen", "zurücksetzen"),
    ("Zurueck", "Zurück"),
    ("abschliessbar", "abschließbar"),
    ("abschliessen", "abschließen"),
    ("Ausfuehrliche", "Ausführliche"),
    ("Ausfuehrungen", "Ausführungen"),
    ("Ausfuehrungs", "Ausführungs"),
    ("Ausfuehrung", "Ausführung"),
    ("einfuegen", "einfügen"),
    ("ausfuehren", "ausführen"),
    ("edge-status (JSON) oeffnen", "edge-status (JSON) öffnen"),
    ("Paper-Trading oeffnen", "Paper-Trading öffnen"),
    ("Einzahlung oeffnen", "Einzahlung öffnen"),
    ("Journal oeffnen", "Journal öffnen"),
    ("Live-Terminal oeffnen", "Live-Terminal öffnen"),
    ("Danach oeffnen wir", "Danach öffnen wir"),
    ("Oeffne", "Öffne"),
    ("oeffne", "öffne"),
    ("geoeffnet", "geöffnet"),
    ("Oeffnen", "Öffnen"),
    ("oeffnen", "öffnen"),
    ("Schliessen", "Schließen"),
    ("schliessen", "schließen"),
    ("Risikopruefung", "Risikoprüfung"),
    ("Pruefung", "Prüfung"),
    ("Pruefen", "Prüfen"),
    ("Pruefe", "Prüfe"),
    ("pruefen", "prüfen"),
    ("Zuversicht (Entscheidung)", "Entscheidungssicherheit (Confidence)"),
    ("Waehlen", "Wählen"),
    ("waehlen", "wählen"),
    ("Aenderungen", "Änderungen"),
    ("Aenderung", "Änderung"),
    ("aenderung", "änderung"),
    ("Aendern", "Ändern"),
    ("aendern", "ändern"),
    ("Koennen", "Können"),
    ("koennen wir", "können wir"),
    ("koennen", "können"),
    ("muessten", "müssten"),
    ("muessen", "müssen"),
    ("duerfen", "dürfen"),
    ("moechtest", "möchtest"),
    ("moechte", "möchte"),
    ("Moeglichkeit", "Möglichkeit"),
    ("Moegliche", "Mögliche"),
    ("moeglich", "möglich"),
    ("Oberflaeche", "Oberfläche"),
    ("zuverlaessig", "zuverlässig"),
    ("erklaert", "erklärt"),
    ("Naechste", "Nächste"),
    ("naechsten", "nächsten"),
    ("naechste", "nächste"),
    ("Menuepunkte", "Menüpunkte"),
    ("Menues", "Menüs"),
    ("Menue", "Menü"),
    ("vollstaendigen", "vollständigen"),
    ("Vollstaendige", "Vollständige"),
    ("vollstaendig", "vollständig"),
    ("laeuft nichts", "läuft nichts"),
    ("laeuft,", "läuft,"),
    ("laeuft", "läuft"),
    ("laesst sich", "lässt sich"),
    ("laesst", "lässt"),
    ("laenger", "länger"),
    ("geschuetzt", "geschützt"),
    ("Gueltigkeit", "Gültigkeit"),
    ("ungueltig", "ungültig"),
    ("gueltig", "gültig"),
    ("Einschaetzungen", "Einschätzungen"),
    ("Einschaetzung", "Einschätzung"),
    ("einschaetzen", "einschätzen"),
    ("Kaufvertraege", "Kaufverträge"),
    ("Vertraege", "Verträge"),
    ("Boersenorders", "Börsenorders"),
    ("Boersen-Geheimnisse", "Börsen-Geheimnisse"),
    ("Boersen-API", "Börsen-API"),
    ("an die Boerse", "an die Börse"),
    ("Boersen", "Börsen"),
    ("Boerse", "Börse"),
    ("Dafuer", "Dafür"),
    ("dafuer", "dafür"),
    ("Fuer", "Für"),
    ("fuer", "für"),
    ("Ueberspringen", "Überspringen"),
    ("ueberspringen", "überspringen"),
    ("ueberspringe", "überspringe"),
    ("Ueberblick", "Überblick"),
    ("Uebersicht", "Übersicht"),
    ("Ueber", "Über"),
    ("ueber", "über"),
    ("Spaeter", "Später"),
    ("spaeter", "später"),
    ("Noetig", "Nötig"),
    ("noetig", "nötig"),
    ("heisst", "heißt"),
    ("weisst", "weißt"),
    ("Verfuegung", "Verfügung"),
    ("nicht verfuegbar", "nicht verfügbar"),
    ("verfuegbar", "verfügbar"),
    ("Staerke", "Stärke"),
    ("juengsten", "jüngsten"),
    ("Haeufige", "Häufige"),
    ("Laeufe", "Läufe"),
    ("gruen", "grün"),
    ("Gruende", "Gründe"),
    ("zu gross", "zu groß"),
    ("gross", "groß"),
    ("Veroeffentlicht", "Veröffentlicht"),
    ("oeffentliche", "öffentliche"),
    ("Taegliche", "Tägliche"),
    ("Abzuege", "Abzüge"),
    ("Eroeffnungen", "Eröffnungen"),
    ("bestaetigen", "bestätigen"),
    ("hauefigsten", "häufigsten"),
    ("Einfuehrung", "Einführung"),
    ("kuenftigen", "künftigen"),
    ("kuerzen", "kürzen"),
    ("fuellen", "füllen"),
    ("Einschraenkungen", "Einschränkungen"),
    ("Einschraenkung", "Einschränkung"),
    ("Uebungsbuch", "Übungsbuch"),
    ("Ueben oder live", "Üben oder live"),
    ("Ueben", "Üben"),
    ("mit Paper ueben", "mit Paper üben"),
    ("so uebst du", "so übst du"),
    ("ueben", "üben"),
    ("Uebung", "Übung"),
    ("Faehigkeitsdaten", "Fähigkeitsdaten"),
    ("Faehigkeiten", "Fähigkeiten"),
    ("Zielport laeuft nichts", "Zielport läuft nichts"),
    ("waechst", "wächst"),
    ("aeltere Version", "ältere Version"),
    # Rest-Treffer (häufig in älteren Strings)
    ("Zielport laeuft", "Zielport läuft"),
    ("Gateway laeuft", "Gateway läuft"),
    ("Stack laeuft", "Stack läuft"),
    ("Dienst laeuft", "Dienst läuft"),
    ("Orchestrator laeuft", "Orchestrator läuft"),
    ("LLM-Dienst laeuft", "LLM-Dienst läuft"),
    ("haengt", "hängt"),
    ("Haengt", "Hängt"),
    ("Stoerungen", "Störungen"),
    ("ueberhaupt", "überhaupt"),
    ("Ueberhaupt", "Überhaupt"),
    ("koennte", "könnte"),
    ("Koennen", "Können"),
    ("muesste", "müsste"),
    ("duerfte", "dürfte"),
    ("aussen", "außen"),
    ("Aussen", "Außen"),
    ("ausschliess", "ausschließ"),
    ("Ausschliess", "Ausschließ"),
    ("Fuehr", "Führ"),
    ("fuehr", "führ"),
    ("fuehlt", "fühlt"),
    ("Fuehlt", "Fühlt"),
    ("fuehren", "führen"),
    ("Fuehren", "Führen"),
    ("verstaend", "verständ"),
    ("Verstaend", "Verständ"),
    ("veraender", "veränder"),
    ("Veraender", "Veränder"),
    ("veraend", "veränd"),
    ("Veraend", "Veränd"),
    ("begruess", "begrüß"),
    ("Begruess", "Begrüß"),
    ("heiss", "heiß"),
    ("Heiss", "Heiß"),
    ("Schaetz", "Schätz"),
    ("schaetz", "schätz"),
    ("naechster", "nächster"),
    ("Naechster", "Nächster"),
    ("Rueck", "Rück"),
    ("rueck", "rück"),
    ("Woerter", "Wörter"),
    ("woerter", "wörter"),
    ("Glueck", "Glück"),
    ("glueck", "glück"),
    ("groessen", "größen"),
    ("Groessen", "Größen"),
    ("laedst", "lädst"),
    ("Laedst", "Lädst"),
    ("schaetzen", "schätzen"),
    ("Schaetzen", "Schätzen"),
    ("betaetigen", "betätigen"),
    ("Betaetigen", "Betätigen"),
    ("Quelle", "Quelle"),
]

SAFE_TAIL = [
    ("Ausfuehr", "Ausführ"),
    ("ausfuehr", "ausführ"),
    ("Zurueck", "Zurück"),
    ("zurueck", "zurück"),
    ("Faehig", "Fähig"),
    ("faehig", "fähig"),
    ("uebrig", "übrig"),
    ("Uebrig", "Übrig"),
]


def apply_pairs(text: str, pairs: list[tuple[str, str]]) -> str:
    for old, new in pairs:
        text = text.replace(old, new)
    return text


def main() -> int:
    raw = DE_PATH.read_text(encoding="utf-8")
    out = apply_pairs(raw, REPLACEMENTS)
    out = apply_pairs(out, SAFE_TAIL)

    try:
        json.loads(out)
    except json.JSONDecodeError as e:
        print("JSON error:", e, file=sys.stderr)
        return 1

    DE_PATH.write_text(out, encoding="utf-8", newline="\n")
    print("OK:", DE_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
