ALTER TABLE features.candle_features
    ADD COLUMN IF NOT EXISTS spread_bps double precision,
    ADD COLUMN IF NOT EXISTS bid_depth_usdt_top25 double precision,
    ADD COLUMN IF NOT EXISTS ask_depth_usdt_top25 double precision,
    ADD COLUMN IF NOT EXISTS orderbook_imbalance double precision,
    ADD COLUMN IF NOT EXISTS depth_balance_ratio double precision,
    ADD COLUMN IF NOT EXISTS depth_to_bar_volume_ratio double precision,
    ADD COLUMN IF NOT EXISTS impact_buy_bps_5000 double precision,
    ADD COLUMN IF NOT EXISTS impact_sell_bps_5000 double precision,
    ADD COLUMN IF NOT EXISTS impact_buy_bps_10000 double precision,
    ADD COLUMN IF NOT EXISTS impact_sell_bps_10000 double precision,
    ADD COLUMN IF NOT EXISTS execution_cost_bps double precision,
    ADD COLUMN IF NOT EXISTS volatility_cost_bps double precision,
    ADD COLUMN IF NOT EXISTS funding_rate double precision,
    ADD COLUMN IF NOT EXISTS funding_rate_bps double precision,
    ADD COLUMN IF NOT EXISTS funding_cost_bps_window double precision,
    ADD COLUMN IF NOT EXISTS open_interest double precision,
    ADD COLUMN IF NOT EXISTS open_interest_change_pct double precision,
    ADD COLUMN IF NOT EXISTS orderbook_age_ms bigint,
    ADD COLUMN IF NOT EXISTS funding_age_ms bigint,
    ADD COLUMN IF NOT EXISTS open_interest_age_ms bigint,
    ADD COLUMN IF NOT EXISTS liquidity_source text,
    ADD COLUMN IF NOT EXISTS funding_source text,
    ADD COLUMN IF NOT EXISTS open_interest_source text;
