# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timesfm_inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'timesfm_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17timesfm_inference.proto\x12\x0f\x61pex.timesfm.v1\"E\n\nTimeSeries\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x15\n\rvalues_f32_le\x18\x02 \x01(\x0c\x12\x0e\n\x06length\x18\x03 \x01(\x05\"n\n\x13PredictBatchRequest\x12+\n\x06series\x18\x01 \x03(\x0b\x32\x1b.apex.timesfm.v1.TimeSeries\x12\x18\n\x10\x66orecast_horizon\x18\x02 \x01(\x05\x12\x10\n\x08model_id\x18\x03 \x01(\t\"L\n\x0e\x46orecastTensor\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x17\n\x0f\x66orecast_f32_le\x18\x02 \x01(\x0c\x12\x0f\n\x07horizon\x18\x03 \x01(\x05\"m\n\x14PredictBatchResponse\x12\x32\n\tforecasts\x18\x01 \x03(\x0b\x32\x1f.apex.timesfm.v1.ForecastTensor\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\"H\n\tTickFrame\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\r\n\x05ts_ms\x18\x03 \x01(\x03\x12\x0b\n\x03seq\x18\x04 \x01(\x05\"|\n\x0fPredictionFrame\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x1d\n\x15point_forecast_f32_le\x18\x02 \x01(\x0c\x12\x0f\n\x07horizon\x18\x03 \x01(\x05\x12\x16\n\x0e\x63omputed_ts_ms\x18\x04 \x01(\x03\x12\x0f\n\x07\x62\x61\x63kend\x18\x05 \x01(\t2\xc0\x01\n\x10TimesFmInference\x12[\n\x0cPredictBatch\x12$.apex.timesfm.v1.PredictBatchRequest\x1a%.apex.timesfm.v1.PredictBatchResponse\x12O\n\x0bStreamTicks\x12\x1a.apex.timesfm.v1.TickFrame\x1a .apex.timesfm.v1.PredictionFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timesfm_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESERIES']._serialized_start=44
  _globals['_TIMESERIES']._serialized_end=113
  _globals['_PREDICTBATCHREQUEST']._serialized_start=115
  _globals['_PREDICTBATCHREQUEST']._serialized_end=225
  _globals['_FORECASTTENSOR']._serialized_start=227
  _globals['_FORECASTTENSOR']._serialized_end=303
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=305
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=414
  _globals['_TICKFRAME']._serialized_start=416
  _globals['_TICKFRAME']._serialized_end=488
  _globals['_PREDICTIONFRAME']._serialized_start=490
  _globals['_PREDICTIONFRAME']._serialized_end=614
  _globals['_TIMESFMINFERENCE']._serialized_start=617
  _globals['_TIMESFMINFERENCE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
