# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared_py.rpc.apex_timesfm.v1 import timesfm_inference_pb2 as timesfm__inference__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in timesfm_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimesFmInferenceStub(object):
    """Zero-Shot-Zeitreihenvorhersage (TimesFM / Foundation-Model-Backend).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictBatch = channel.unary_unary(
                '/apex.timesfm.v1.TimesFmInference/PredictBatch',
                request_serializer=timesfm__inference__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=timesfm__inference__pb2.PredictBatchResponse.FromString,
                _registered_method=True)
        self.StreamTicks = channel.stream_stream(
                '/apex.timesfm.v1.TimesFmInference/StreamTicks',
                request_serializer=timesfm__inference__pb2.TickFrame.SerializeToString,
                response_deserializer=timesfm__inference__pb2.PredictionFrame.FromString,
                _registered_method=True)


class TimesFmInferenceServicer(object):
    """Zero-Shot-Zeitreihenvorhersage (TimesFM / Foundation-Model-Backend).
    """

    def PredictBatch(self, request, context):
        """Batch: mehrere Assets gleichzeitig (GPU-freundliche Bündelung serverseitig).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTicks(self, request_iterator, context):
        """Bidirektionales Streaming: kontinuierliche Tick-Updates -> inkrementelle Vorhersagen.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimesFmInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=timesfm__inference__pb2.PredictBatchRequest.FromString,
                    response_serializer=timesfm__inference__pb2.PredictBatchResponse.SerializeToString,
            ),
            'StreamTicks': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTicks,
                    request_deserializer=timesfm__inference__pb2.TickFrame.FromString,
                    response_serializer=timesfm__inference__pb2.PredictionFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apex.timesfm.v1.TimesFmInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apex.timesfm.v1.TimesFmInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimesFmInference(object):
    """Zero-Shot-Zeitreihenvorhersage (TimesFM / Foundation-Model-Backend).
    """

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apex.timesfm.v1.TimesFmInference/PredictBatch',
            timesfm__inference__pb2.PredictBatchRequest.SerializeToString,
            timesfm__inference__pb2.PredictBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTicks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/apex.timesfm.v1.TimesFmInference/StreamTicks',
            timesfm__inference__pb2.TickFrame.SerializeToString,
            timesfm__inference__pb2.PredictionFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
